package com.supplychain.common.dto;

import com.supplychain.common.event.TransactionType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class OrderRequestDto {
    private Integer userId;
    private Integer productId;
    private Double amount; // Represents price or quantity depending on business logic
    private UUID orderId;  // Generated by the client or service
    private TransactionType transactionType;
}